port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090
experimental:
  ignore-resolve-fail: true
dns:
  enable: true
  enhanced-mode: fake-ip
  nameserver:
    - 1.1.1.2
    - 9.9.9.9
    - 208.67.220.220
    - 208.67.222.222
    - 1.0.0.1
    - 1.1.1.1
    - 8.8.8.8
  fake-ip-filter:
    - +.stun.*.*
    - +.stun.*.*.*
    - +.stun.*.*.*.*
    - +.stun.*.*.*.*.*
    - "*.n.n.srv.nintendo.net"
    - +.stun.playstation.net
    - xbox.*.*.microsoft.com
    - "*.*.xboxlive.com"
    - "*.msftncsi.com"
    - "*.msftconnecttest.com"
    - WORKGROUP
store-fake-ip: true
tun:
  enable: true
  stack: gvisor
  auto-route: true
  auto-detect-interface: true
  dns-hijack:
    - any:53

proxies:
  - name: Cna 00
    type: vmess
    server: www.seenco.ir
    port: 443
    uuid: 51b34f70-5044-5389-97c5-15271cc96ac7
    alterId: 0
    cipher: chacha20-poly1305
    tls: true
    network: ws
    ws-path: /
    ws-headers:
      Host: www.seenco.ir
  - name: Cna 01
    type: vmess
    server: ws1.seenco.ir
    port: 443
    uuid: 51b34f70-5044-5389-97c5-15271cc96ac7
    alterId: 0
    cipher: chacha20-poly1305
    tls: true
    network: ws
    ws-path: /
    ws-headers:
      Host: ws1.seenco.ir
  - name: Cna 02
    type: vmess
    server: ws2.seenco.ir
    port: 443
    uuid: 51b34f70-5044-5389-97c5-15271cc96ac7
    alterId: 0
    cipher: chacha20-poly1305
    tls: true
    network: ws
    ws-path: /
    ws-headers:
      Host: ws2.seenco.ir
proxy-groups:
  - name: CnaHa
    type: url-test
    proxies:
      - Cna 00
      - Cna 01
      - Cna 02
    url: https://www.youtube.com
    interval: 60
rule-providers:
  dns:
    behavior: classical
    type: http
    url: https://cdn.jsdelivr.net/gh/dariuosh/clashassets@main/Data/dns.yaml
    interval: 3600
    path: /dns.yaml
  telegram:
    behavior: classical
    type: http
    url: https://cdn.jsdelivr.net/gh/dariuosh/clashassets@main/Data/telegram.yaml
    interval: 3590
    path: /telegram.yaml
  open:
    behavior: classical
    type: http
    url: https://cdn.jsdelivr.net/gh/dariuosh/clashassets@main/Data/open.yaml
    interval: 3580
    path: /open.yaml

rules:
  - IP-CIDR,192.168.0.0/16,DIRECT
  - IP-CIDR,172.16.0.0/12,DIRECT
  - IP-CIDR,127.0.0.0/8,DIRECT

  - DST-PORT,53,CnaHa
  - RULE-SET,dns,CnaHa
  - RULE-SET,telegram,CnaHa
  - RULE-SET,open,CnaHa

  - MATCH,DIRECT
cfw-bypass:
  - localhost
  - 127.*
  - 10.*
  - 172.16.*
  - 172.17.*
  - 172.18.*
  - 172.19.*
  - 172.20.*
  - 172.21.*
  - 172.22.*
  - 172.23.*
  - 172.24.*
  - 172.25.*
  - 172.26.*
  - 172.27.*
  - 172.28.*
  - 172.29.*
  - 172.30.*
  - 172.31.*
  - 192.168.*
  - <local>
cfw-latency-timeout: 5000
